name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Composer
        uses: php-actions/composer@v6

      - name: Build
        run: npm install && npm run production

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Deploy files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: '${{ secrets.SERVER_LOGIN }}'
          server: 'db.coastcowconsumer.com'
          ssh_private_key: ${{ secrets.PARTHS_PRIVATE_KEY }}
          remote_path: '/var/www/html'
          sftp_only: 'yes'
