name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: 'gitactions'
          password: ${{ secrets.SFTP_PASSWORD_ACTIONS }}
          server: 'db.coastcowconsumer.com'
          ssh_private_key: 'if password is set, this will be ignored'
          remote_path: '/var/www/html'
          sftp_only: 'yes'
