name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy files
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: '${{ secrets.SERVER_LOGIN }}'
          server: 'db.coastcowconsumer.com'
          port: '25060'
          ssh_private_key: ${{ secrets.PARTHS_PRIVATE_KEY }}
          local_path: '../*'
          remote_path: '/var/www/html'
          sftpArgs: '-o ConnectTimeout=5'
          sftp_only: 'yes'
